name: API Schema Check

on:
  pull_request:
    paths:
      - 'api/v2.0/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
      - uses: delimit-ai/delimit-action@afa76ce3d1caa90a8de6bfd038471af672f60e90
        with:
          spec: api/v2.0/swagger.yaml
